[package]
name = "kvs"
version = "0.1.0"
authors = ["Nick Magerko <>"]
edition = "2018"

[dependencies]
failure = "0.1.5"
failure_derive = "0.1.5"
structopt = "0.2.16"

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
tempfile = "3.0.7"
walkdir = "2.2.7"
